---

- name: Installation des paquets de base
  hosts: 127.0.0.1
  connection: local
  become: yes

  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list

  tasks:
    - name: Vérification de l'existence du fichier {{apt_file}}
      command: test -f {{apt_file}}
      register: google_apt_exists
      ignore_errors: True

    - name: Ajout de la clé pour Google Chrome
      shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      when: google_apt_exists.rc == 1

    - name: Ajout du dépôt pour Google Chrome
      copy:
          content: "deb http://dl.google.com/linux/chrome/deb/ stable main"
          dest: "{{apt_file}}"
          owner: root
          group: root
          mode: 644
      when: google_apt_exists.rc == 1

    - name: Mise à jour d'apt
      apt:
          update_cache: yes
      when: google_apt_exists.rc == 1

    - name: Installation de Google Chrome
      apt:
          pkg: google-chrome-stable
          state: installed
