---

- name: Installation de Virtualbox
  hosts: 127.0.0.1
  connection: local
  become: yes

  vars:
    - apt_file: /etc/apt/sources.list.d/virtualbox.list

  tasks:
    - name: Vérification de l'existence du fichier {{apt_file}}
      command: test -f {{apt_file}}
      register: virtualbox_apt_exists
      ignore_errors: True

    - name: Ajout de la première clé pour Virtualbox
      apt_key:
          url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
          state: present
      when: virtualbox_apt_exists.rc == 1

    - name: Ajout de la seconde clé pour Virtualbox
      apt_key:
          url: https://www.virtualbox.org/download/oracle_vbox.asc
          state: present
      when: virtualbox_apt_exists.rc == 1

    - name: Ajout du dépôt pour Virtualbox
      copy:
          content: "deb http://download.virtualbox.org/virtualbox/debian stretch contrib"
          dest: "{{apt_file}}"
          owner: root
          group: root
          mode: 644
      when: virtualbox_apt_exists.rc == 1

    - name: Mise à jour d'apt
      apt:
          update_cache: yes
      when: virtualbox_apt_exists.rc == 1

    - name: Installation de Virtualbox
      apt:
          pkg: virtualbox-6.0
          state: installed
